# crea una funcion que reciba un texto
# el cual debe returnar verdadero o falso
# si el texto es un polindromo


def is_polindromo(texto: str) -> bool:
    texto = texto.replace(" ", "").lower()
    texto_invertido = texto[::-1]
    return texto_invertido == texto


lista_palabras = [
    "ala",
    "radar",
    "nivel",
    "reconocer",
    "anilina",
    "salas",
    "oro",
    "oso",
    "rallar",
    "arenera",
    "somas",
    "solos",
    "seres",
    "somos",
    "anilina",
    "aza",
    "aviva",
    "otto",
    "ababa",
    "aibofobia",
    "casa",
    "perro",
    "gato",
    "mesa",
    "silla",
    "carro",
    "árbol",
    "programacion",
    "universidad",
    "computadora",
    "teléfono",
    "ventana",
    "puerta",
    "reloj",
    "teclado",
    "ratón",
    "zapato",
    "libro",
    "cuaderno",
    "lámpara",
    "bicicleta",
    "montaña",
    "cielo",
    "nube",
    "estrella",
    "sol",
    "luna",
    "mar",
    "río",
    "avión",
    "La casa es grande",
    "El perro ladra fuerte",
    "Me gusta programar",
    "Hoy es un buen día",
    "Ella tiene una bicicleta roja",
    "El cielo está azul",
    "Las estrellas brillan",
    "Voy a la universidad",
    "Necesito una computadora nueva",
    "El libro está en la mesa",
    "La lámpara está encendida",
    "Tengo una montaña de tareas",
    "El gato duerme en la silla",
    "La ventana está abierta",
    "La puerta está cerrada",
    "El avión despega",
    "El mar es inmenso",
    "El reloj marca las tres",
    "Voy a comprar un zapato",
    "La luna está llena",
    "El sol brilla en el cielo",
    "El río es caudaloso",
    "Tengo que usar el teléfono",
    "El cuaderno está lleno de notas",
    "El teclado está sucio",
    "La nube cubre el sol",
    "Necesito una lámpara nueva",
    "Anita lava la tina",
    "A mamá Roma le aviva el amor a mamá",
    "Amo la pacífica paloma",
    "Dábale arroz a la zorra el abad",
    "La ruta natural",
    "No subas, abusón",
    "Yo hago yoga hoy",
    "A ti no, bonita",
]


for palabra in lista_palabras:
    result = is_polindromo(palabra)
    print(f"{palabra}: {result}")
